# Generated by Django 5.2.17 on 2026-09-05 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                ("date_debut", models.DateTimeField(verbose_name="Date de début")),
                (
                    "date_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                ("lieu", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "organisateur",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Organisateur"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("en_cours", "En cours"),
                            ("passe", "Déjà eu lieu"),
                        ],
                        default="a_venir",
                        max_length=20,
                    ),
                ),
                (
                    "image_principale",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activites/",
                        verbose_name="Image principale",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
                "ordering": ["date_debut"],
            },
        ),
        migrations.CreateModel(
            name="CategoriePatrimoine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
            ],
            options={
                "verbose_name": "Catégorie de patrimoine",
                "verbose_name_plural": "Catégories de patrimoine",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("objet", models.CharField(max_length=200, verbose_name="Objet")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "date_envoi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'envoi"
                    ),
                ),
                ("lu", models.BooleanField(default=False, verbose_name="Lu")),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-date_envoi"],
            },
        ),
        migrations.CreateModel(
            name="PageInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("contenu", models.TextField(verbose_name="Contenu")),
                (
                    "image_tete",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/",
                        verbose_name="Image d'en-tête",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Page d'information",
                "verbose_name_plural": "Pages d'information",
                "ordering": ["titre"],
            },
        ),
        migrations.CreateModel(
            name="GalerieImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="activites/galerie/", verbose_name="Image"
                    ),
                ),
                (
                    "legende",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                ("ordre", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="village.activite",
                        verbose_name="Activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de galerie",
                "verbose_name_plural": "Images de galerie",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Patrimoine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="patrimoine/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="URL de la vidéo"),
                ),
                (
                    "localisation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Localisation"
                    ),
                ),
                (
                    "createur",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Créateur / Détenteur du savoir",
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patrimoines",
                        to="village.categoriepatrimoine",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de patrimoine",
                "verbose_name_plural": "Éléments de patrimoine",
                "ordering": ["-date_ajout"],
            },
        ),
    ]
