# Generated by Django 5.2.17 on 2026-09-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="Adresse IP")),
                (
                    "username",
                    models.CharField(max_length=150, verbose_name="Nom d'utilisateur"),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Heure de la tentative"
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="Réussie")),
            ],
            options={
                "verbose_name": "Tentative de connexion",
                "verbose_name_plural": "Tentatives de connexion",
                "ordering": ["-attempt_time"],
            },
        ),
        migrations.CreateModel(
            name="VisitCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="Chemin URL"
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de visites"
                    ),
                ),
                (
                    "last_visit",
                    models.DateTimeField(auto_now=True, verbose_name="Dernière visite"),
                ),
            ],
            options={
                "verbose_name": "Compteur de visite",
                "verbose_name_plural": "Compteurs de visite",
                "ordering": ["-count"],
            },
        ),
    ]
